### ISSUE TITLE
Absolute path python bin

### ISSUE THREAD

**Issue by daniele-sartiano** [amazon-research/datatuner#2]
In the file:

https://github.com/amazon-research/datatuner/blob/e240144710a499fa18f5f40b3c5ffbf33b2ecfa3/src/datatuner/lm/metrics.py#L23

there is the absolute path of Python bin.
For this reason, I am not able to run the ```evaluate_lm.sh``` script.
It would be better to use a relative path.

**Comment by isabel-groves** [comment]
Thanks for raising this. Update in latest version
